import { Controller, Post, Body, HttpCode, HttpStatus } from '@nestjs/common';
import { ApiTags, ApiOperation, ApiResponse, ApiProperty } from '@nestjs/swagger';
import { PatientAuthService } from './patient-auth.service';
import { IsString, IsNotEmpty } from 'class-validator';

class MobileLoginDto {
  @ApiProperty({ example: 'uuid-1234', description: 'The unique ID of the patient given by therapist' })
  @IsString()
  @IsNotEmpty()
  patientId: string;

  @ApiProperty({ example: '123456', description: 'The 6-digit PIN generated by therapist' })
  @IsString()
  @IsNotEmpty()
  accessCode: string;
}

@ApiTags('Mobile Auth')
@Controller('auth/patient')
export class MobileAuthController {
  constructor(private readonly patientAuthService: PatientAuthService) { }

  @Post('login')
  @HttpCode(HttpStatus.OK)
  @ApiOperation({ summary: 'Login for Mobile App using PIN' })
  @ApiResponse({ status: 200, description: 'Returns JWT Token' })
  @ApiResponse({ status: 401, description: 'Invalid PIN or ID' })
  async login(@Body() loginDto: MobileLoginDto) {
    return this.patientAuthService.login(loginDto.patientId, loginDto.accessCode);
  }
}
