/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.symma.app.data.remote.model.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param id 
 * @param name 
 * @param keyName 
 * @param type 
 * @param category 
 * @param description 
 * @param mobileModule Mobile module for strategy selection (SMILE, BROWS, JAW, KISS, EYES, EYES_INVERSE)
 * @param assetAnimationUrl 
 * @param assetTutorialVideoUrl 
 */


data class ActiveRoutineExerciseDto (

    @SerializedName("id")
    val id: kotlin.String,

    @SerializedName("name")
    val name: kotlin.String,

    @SerializedName("keyName")
    val keyName: kotlin.String,

    @SerializedName("type")
    val type: kotlin.String,

    @SerializedName("category")
    val category: kotlin.String,

    @SerializedName("description")
    val description: kotlin.Any? = null,

    /* Mobile module for strategy selection (SMILE, BROWS, JAW, KISS, EYES, EYES_INVERSE) */
    @SerializedName("mobileModule")
    val mobileModule: kotlin.Any? = null,

    @SerializedName("assetAnimationUrl")
    val assetAnimationUrl: kotlin.Any? = null,

    @SerializedName("assetTutorialVideoUrl")
    val assetTutorialVideoUrl: kotlin.Any? = null

)

