/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.symma.app.data.remote.model.models

import com.symma.app.data.remote.model.models.ActiveRoutineExerciseDto

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param id 
 * @param orderIndex 
 * @param sets Number of sets for this exercise
 * @param repsPerSet Number of repetitions per set
 * @param targetHoldSeconds Hold time in seconds (0 for isotonic exercises)
 * @param restBetweenSets Rest time between sets in seconds
 * @param difficultyLevel Difficulty level multiplier (1.0 = normal)
 * @param strictMode Whether strict mode is enabled
 * @param exercise 
 */


data class ActiveRoutineItemDto (

    @SerializedName("id")
    val id: kotlin.String,

    @SerializedName("orderIndex")
    val orderIndex: java.math.BigDecimal,

    /* Number of sets for this exercise */
    @SerializedName("sets")
    val sets: java.math.BigDecimal,

    /* Number of repetitions per set */
    @SerializedName("repsPerSet")
    val repsPerSet: java.math.BigDecimal,

    /* Hold time in seconds (0 for isotonic exercises) */
    @SerializedName("targetHoldSeconds")
    val targetHoldSeconds: java.math.BigDecimal,

    /* Rest time between sets in seconds */
    @SerializedName("restBetweenSets")
    val restBetweenSets: java.math.BigDecimal,

    /* Difficulty level multiplier (1.0 = normal) */
    @SerializedName("difficultyLevel")
    val difficultyLevel: java.math.BigDecimal,

    /* Whether strict mode is enabled */
    @SerializedName("strictMode")
    val strictMode: kotlin.Boolean,

    @SerializedName("exercise")
    val exercise: ActiveRoutineExerciseDto

)

