/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.symma.app.data.remote.model.models

import com.symma.app.data.remote.model.models.ActiveRoutineItemDto

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param id 
 * @param name 
 * @param startDate 
 * @param status 
 * @param items 
 * @param endDate 
 */


data class ActiveRoutineResponseDto (

    @SerializedName("id")
    val id: kotlin.String,

    @SerializedName("name")
    val name: kotlin.String,

    @SerializedName("startDate")
    val startDate: kotlin.String,

    @SerializedName("status")
    val status: kotlin.String,

    @SerializedName("items")
    val items: kotlin.collections.List<ActiveRoutineItemDto>,

    @SerializedName("endDate")
    val endDate: kotlin.Any? = null

)

