/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.symma.app.data.remote.model.models

import com.symma.app.data.remote.model.models.SessionItemDto

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param routineId 
 * @param startTime 
 * @param endTime 
 * @param items 
 */


data class CreateSessionDto (

    @SerializedName("routineId")
    val routineId: kotlin.String,

    @SerializedName("startTime")
    val startTime: kotlin.String,

    @SerializedName("endTime")
    val endTime: kotlin.String,

    @SerializedName("items")
    val items: kotlin.collections.List<SessionItemDto>

)

