/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.symma.app.data.remote.model.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param exerciseId 
 * @param repsCompleted 
 * @param difficulty 
 * @param averageAccuracy Average symmetry score (0-100)
 * @param seriesData Detailed series data
 */


data class SessionItemDto (

    @SerializedName("exerciseId")
    val exerciseId: kotlin.String,

    @SerializedName("repsCompleted")
    val repsCompleted: java.math.BigDecimal,

    @SerializedName("difficulty")
    val difficulty: java.math.BigDecimal? = java.math.BigDecimal("0"),

    /* Average symmetry score (0-100) */
    @SerializedName("averageAccuracy")
    val averageAccuracy: java.math.BigDecimal? = null,

    /* Detailed series data */
    @SerializedName("seriesData")
    val seriesData: kotlin.Any? = null

)

